CREATE USER C##usuarios IDENTIFIED BY usuarios123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO C##usuarios;
GRANT ALL PRIVILEGES TO C##usuarios;
GRANT UNLIMITED TABLESPACE TO C##usuarios;